version: '3.9'

services:
  backend:
    build: ./aideck/backend
    container_name: aideck-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./aideck/backend:/app

  db:
    image: postgres:15
    container_name: aideck-db
    restart: always
    environment:
      POSTGRES_USER: aideck
      POSTGRES_PASSWORD: aideckpass
      POSTGRES_DB: aideck_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: aideck-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: aideck-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana:/var/lib/grafana

volumes:
  pgdata:
