version: '3.8'
services:
  backend:
    build: ./aideck/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  frontend:
    build: ./aideck/frontend
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: aideck
      POSTGRES_PASSWORD: aideck
      POSTGRES_DB: aideck
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
