# Simple deployment automation for aideck (Docker Compose)
name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./aideck/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aideck-backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./aideck/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aideck-frontend:latest
      - name: Deploy to server (example)
        run: |
          echo "Deploy step: use SSH or cloud provider action here"
